name: Continuous Integration
on: [push]

env:
  CI: true

jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the code
        uses: actions/checkout@v2

      # https://github.com/actions/setup-node
      - name: Setup Node.js 12.18.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.1

      # https://github.com/actions/cache
      - name: Yarn cache - get directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      # https://github.com/actions/cache
      - name: Yarn cache - enable it
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --production=false

      - name: Build
        run: yarn build
